version: '3'

services:
  reverse-proxy:
    #restart: always
    image: traefik
    command: --api --docker
    ports:
      - "82:80"     # The HTTP port
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web_nw
  www:
    #restart: always
    image: nginx
    tty: true
    stdin_open: true
    volumes:
      - ./conf/nginx/www.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    labels:
      - "traefik.frontend.rule=Host:auth.epic.lc"
    depends_on:
      - flaskapp
    networks:
      - web_nw
  flaskapp:
    #restart: always
    build: .
    expose:
      - 5000
    volumes:
      - .:/opt/services/flaskapp/src
    depends_on:
      - sqldb
    networks:
      - db_nw
      - web_nw
  sqldb:
    image: mariadb
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rEEKbU7fHK3C
      MYSQL_DATABASE: epic
      MYSQL_USER: epicrpg
      MYSQL_PASSWORD: e36BbwM2x6Tm
    ports:
      - "3309:3306"
    volumes:
      - ./conf/db/auth.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - db_nw
    container_name: EpicDb
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge