version: '3'

services:
  www:
    restart: "no"
    image: nginx
    tty: true
    stdin_open: true
    volumes:
      - /home/alex/WebstormProjects/epic-front:/var/www/html
      - ./conf/nginx/www.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flaskapp
    ports:
    - 80:80
    networks:
      - default
      - epic-chat_default
  flaskapp:
    build: .
    restart: "no"
    volumes:
      - .:/opt/services/flaskapp/src
    expose:
      - 5000
    networks:
      - default
      - epic-common_default
  chatapp:
    build: ./chat/
    restart: "no"
    volumes:
      - ./chat/:/opt/services/chat
    expose:
      - 5678
    ports:
    - 127.0.0.1:5678:5678
    networks:
      - default
      - epic-common_default
networks:
  default:
    driver: bridge
  epic-common_default:
    external: true
  epic-chat_default:
    external: true
