version: '3'

services:
  www:
    restart: always
    image: nginx
    tty: true
    stdin_open: true
    volumes:
      - .:/var/www/html
      - ./conf/nginx/www.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flaskapp
    ports:
    - 127.0.0.1:84:80
    networks:
      - default
      - epic-chat_default
  flaskapp:
    build: .
    volumes:
      - .:/opt/services/flaskapp/src
    expose:
      - 5000
    networks:
      - default
      - epic-common_default
networks:
  default:
    driver: bridge
  epic-common_default:
    external: true
  epic-chat_default:
    external: true