version: '3'

services:
  reverse-proxy:
    restart: always
    image: traefik
    command: --api --docker
    ports:
      - "8090:80"     # The HTTP port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - auth_nw
  www:
    restart: always
    image: nginx
    tty: true
    stdin_open: true
    volumes:
      - .:/var/www/html
      - ./conf/nginx/www.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    labels:
      - "traefik.frontend.rule=Host:auth.epic.lc"
    depends_on:
      - flaskapp
    networks:
      - auth_nw
  flaskapp:
    build: .
    volumes:
      - .:/opt/services/flaskapp/src
    expose:
      - 5000
    networks:
      - auth_nw
      - epic-common_default
      - internal-dev
networks:
  auth_nw:
    driver: bridge
  epic-common_default:
    external: true
  internal-dev:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.255.0/28