"""tokens expirations

Revision ID: d7b6b0c9516b
Revises: 82e0f2b8f946
Create Date: 2018-09-03 10:52:31.458124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b6b0c9516b'
down_revision = '82e0f2b8f946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('created_at', sa.Integer(), nullable=True))
    op.add_column('token', sa.Column('expired_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'expired_at')
    op.drop_column('token', 'created_at')
    # ### end Alembic commands ###
